INSERT INTO CAR( NAME, VERSION ,MODEL ) VALUES ('Sentra','Luxury','2008');
INSERT INTO CAR( NAME, VERSION ,MODEL ) VALUES ('Leon','FR','2018');
INSERT INTO CAR( NAME, VERSION ,MODEL ) VALUES ('Versa','XL','2017');

INSERT INTO DRIVER(NAME ,EDAD) VALUES ('Carlos Sanchez','28');
INSERT INTO DRIVER(NAME ,EDAD) VALUES ('Omar Sanchez','28');

INSERT INTO DRIVER_CAR(DRIVER_ID_DRIVER, CAR_ID_CAR) VALUES('1','2');
INSERT INTO DRIVER_CAR(DRIVER_ID_DRIVER, CAR_ID_CAR) VALUES('1','3');
INSERT INTO DRIVER_CAR(DRIVER_ID_DRIVER, CAR_ID_CAR) VALUES('2','1');
